version: '3'

services:

  php:
    user: ${USER_USERNAME:-developer}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_USERNAME: ${USER_USERNAME:-developer}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: signal:dev
    environment:
      USER_USERNAME: ${USER_USERNAME:-vscode}
      USER_UID: ${USER_UID:-1000}
      USER_GID:
    stop_signal: SIGKILL
    command: sleep infinity
    volumes:
      - .:/package
